import Head from "next/head";

import Webcam from "@/components/handpose/Webcam";
import Visualizer3D from "@/components/handpose/Visualizer3D";
import { DetectorProvider } from "@/hooks/DetectorProvider";

export default function RTDetection() {
  return (
    <>
      <Head>
        <title>SignIt | RT Handpose</title>
        <meta name="description" content="Sign language training app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Real <span className="text-[hsl(280,100%,70%)]">Time</span>
          </h1>
          <div className="relative">
            <DetectorProvider>
              <div className="absolute flex flex-1">
                <Visualizer3D />
              </div>
              <Webcam />
            </DetectorProvider>
          </div>
          <p className="text-white">
            Move your hands in front of the camera to see the tracking points
            generated by a machine learning model.
          </p>
        </div>
      </main>
    </>
  );
}
